"""initial_schema

Revision ID: c5a042c433ef
Revises: 
Create Date: 2026-08-17 10:10:56.996713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a042c433ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_doctor_id'), 'doctors', ['doctor_id'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('blood_type', sa.String(length=16), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('chronic_conditions', sa.JSON(), nullable=False),
    sa.Column('current_medications', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.create_table('clinical_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('doctor_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('clinician_notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_clinical_sessions_doctor_id'), 'clinical_sessions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_clinical_sessions_patient_id'), 'clinical_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_sessions_session_id'), 'clinical_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_clinical_sessions_status'), 'clinical_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_clinical_sessions_thread_id'), 'clinical_sessions', ['thread_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_table('cds_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('risk_scores', sa.JSON(), nullable=False),
    sa.Column('differentials', sa.JSON(), nullable=False),
    sa.Column('imaging_findings', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('safety_flags', sa.JSON(), nullable=False),
    sa.Column('symbolic_overrides', sa.JSON(), nullable=False),
    sa.Column('final_status', sa.String(length=64), nullable=False),
    sa.Column('clinician_approval', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cds_results_session_id'), 'cds_results', ['session_id'], unique=True)
    op.create_table('clinical_data_requests',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('requesting_agent', sa.String(length=64), nullable=False),
    sa.Column('pathway_name', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('required_fields', sa.JSON(), nullable=False),
    sa.Column('optional_fields', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('clinician_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['clinical_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_clinical_data_requests_request_id'), 'clinical_data_requests', ['request_id'], unique=False)
    op.create_index(op.f('ix_clinical_data_requests_session_id'), 'clinical_data_requests', ['session_id'], unique=False)
    op.create_index(op.f('ix_clinical_data_requests_status'), 'clinical_data_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_data_requests_status'), table_name='clinical_data_requests')
    op.drop_index(op.f('ix_clinical_data_requests_session_id'), table_name='clinical_data_requests')
    op.drop_index(op.f('ix_clinical_data_requests_request_id'), table_name='clinical_data_requests')
    op.drop_table('clinical_data_requests')
    op.drop_index(op.f('ix_cds_results_session_id'), table_name='cds_results')
    op.drop_table('cds_results')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_clinical_sessions_thread_id'), table_name='clinical_sessions')
    op.drop_index(op.f('ix_clinical_sessions_status'), table_name='clinical_sessions')
    op.drop_index(op.f('ix_clinical_sessions_session_id'), table_name='clinical_sessions')
    op.drop_index(op.f('ix_clinical_sessions_patient_id'), table_name='clinical_sessions')
    op.drop_index(op.f('ix_clinical_sessions_doctor_id'), table_name='clinical_sessions')
    op.drop_table('clinical_sessions')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctors_doctor_id'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
